### ISSUE TITLE
7/17/2017 Meeting

### ISSUE THREAD

**Issue by spinecone** [djangogirlspdx/docs#1]
We are onboarding new organizers Brigette and Rachel! 🎉 

We'll be discussing:
- Timeline for next workshop
- djangogirlspdx.com ? (or, djangowranglers.gov, or whatever)
- Overview of our various applications and accounts:
  - google drive
  - email
  - mailchimp
  - dg admin
  - trello
  - money
  - twitter
  - facebook
- Who does what?
   - treasurer
  - food ordering
  - swag ordering
  - location liaison
  - social media
  - organize/host coach meeting
  - website updates
- Next steps
- The future? 🚀

**Comment by spinecone** [comment]
Next steps:

Terian is gonna
- figure out password management (lastpass is apparently 🗑 )
- Make us a pretty website, probably github pages
- Make hailee + brigette + rachel facebook admins!

Our date is October 14th!!!
Our tentative venue is NXT again! ( rachel )
Contact Claire about making a new event website (brigette)
Contact caterer (brigette)
Make the website look right (rachel + brigette)
Budgeting (but not actual money) rachel
Actual money handling (nate)
Think about finding a dedicated money person for next time
Social media (hailee + brigette)
Write down documentation in here (hailee + nate + terian)

**Comment by rachelleahklein** [comment]
Prior organizers, please share:

- Unexpected issues/things you wish you had known!
- Potential areas of growth/improvement

**Comment by vilmibm** [comment]
our current coffers are at $2,412

**Comment by vilmibm** [comment]
nate is gonna:

- start a new budget spreadsheet
- digitize the rest of the fundraising cash
- update prospectus

**Comment by spinecone** [comment]
Things to think about in the future (after applications are open)
- Get the word out in places we haven't before (newspapers, community colleges, flyers in more places, ask friends to hang flyers for us in their areas)
- Childcare?
- Dietary restrictions?
